blog/urls.py
from django.urls import path



from blog import views


app_name = 'blog'


urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('modify/<int:pk>/', views.modify, name='modify'),

    path('write/', views.write, name='write'),
    

]

common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path



from common import views




app_name = 'common'


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('signup/', views.signup, name='signup'),




]

config/urls.py
from django.contrib import admin
from django.urls import path, include



from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('common/', include('common.urls')),


    path('', views.index),



]

blog/models.py
from tabnanny import verbose
from django.db import models
from django.urls import reverse


from django.conf import settings
from django.contrib.auth import get_user_model
#from django.utils import timezone


# Create your models here.



class Question(models.Model):
    subject = models.CharField(max_length=100)
    content = models.TextField(max_length=1000)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = '작성글'
        verbose_name_plural = '작성글 리스트'

    def get_absolute_url(self):
        return reverse('blog:detail', args=[str(self.pk)])

    def __str__(self):
        return self.subject



class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField(max_length=1000)
    author = settings.AUTH_USER_MODEL
    created_at = models.DateTimeField(auto_now_add=True)   
    
    
    class Meta:
        verbose_name = '댓글'
        verbose_name_plural = '댓글 리스트'


    def __str__(self):
        return self.question

common/models.py
from tabnanny import verbose
from django.db import models

from django.contrib.auth.models import AbstractUser

# Create your models here.

class MyUser(AbstractUser):
    nickname = models.CharField(max_length=20)


    labels = {'nickname':'닉네임',}



    class Meta:
        verbose_name = '유저정보'
        verbose_name_plural = '유저정보 리스트'

blog/forms.py
from django import forms


from blog.models import Question, Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']





class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']

common/forms.py
from django.contrib.auth.forms import UserCreationForm


from django.contrib.auth import get_user_model
from django.conf import settings

class SignupForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'password1', 'password2', 'nickname']

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse


from blog.models import Question, Answer
from blog.forms import QuestionForm, AnswerForm

# Create your views here.



def index(request):
    question_list = Question.objects.all()
    return render(request, 'blog/question_list.html', {'question_list':question_list})
    #return HttpResponse('첫 방문')


def detail(request, pk):
    question = get_object_or_404(Question, pk=pk)
    return render(request, 'blog/question_detail.html', {'question':question})



def write(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.save()
            return redirect('blog:index')
        
    else:
        form = QuestionForm()

    return render(request, 'blog/question_write.html', {'form':form})




def modify(request, pk):
    question = get_object_or_404(Question, pk=pk)
    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.save()
            return redirect('blog:detail', pk=pk)
        
    else:
        form = QuestionForm(instance=question)

    return render(request, 'blog/question_write.html', {'form':form})

common/views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.contrib.auth import login, logout, authenticate


from common.forms import SignupForm

# Create your views here.



def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            row_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=row_password)
            login(request, user)
            return redirect('blog:index')
        
    else:
        form = SignupForm()

    return render(request, 'common/signup.html', {'form':form})

templates/base.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    </head>
    <body>
        <div class="contain">
            <div class="row">
                <div class="col-sm-3">
                </div>

                <div class="col-sm-6 mt-3">
                    <div class="container">
                        <div class="row">
                            <!--크기 조절용-->
                            <div class="col-sm-2 mt-3"></div>

                            <!--메뉴-->
                            <div class="col-sm-8">
                                <div class="border-bottom border-1 mb-3 pb-1 border-primary">
                                    <a href="{% url 'blog:index' %}" class="btn btn-sm btn-primary">홈으로</a>
                                    {% if user.is_authenticated %}
                                        <a href="{% url 'common:logout' %}" class="btn btn-sm btn-primary">[{{ user.nickname }}]로그아웃</a>
                                        <a href="{% url 'blog:write' %}" class="btn btn-sm btn-primary">글작성</a>
                                    {% else %}
                                        <a href="{% url 'common:login' %}" class="btn btn-sm btn-primary">로그인</a> 또는
                                        <a href="{% url 'common:signup' %}" class="btn btn-sm btn-primary">회원가입</a>
                                    {% endif %}
                                </div>

                            </div>
                            <!--크기 조절용-->
                            <div class="col-sm-2 mt-3"></div>
                        </div>


                        <div class="row">
                            <!--크기 조절용-->
                            <div class="col-sm-2 mt-3"></div>
                            <!--컨텐츠-->
                            <div class="col-sm-8">
                                {% block content %}
                                {% endblock %}
                            </div>
                            <!--크기 조절용-->
                            <div class="col-sm-2 mt-3"></div>
                        </div>

                        
                    </div>
                </div>


                <div class="col-sm-3">
                </div>
            </div>

        </div>

    </body>
</html>

templates/blog/question_detail.html
{% extends 'base.html' %}
{% block title %}글 조회{% endblock %}


{% block content %}
<div class="card border-1 border-primary border-rounded">
    <div class="card-body">
        <h6>작성자 : {{ question.author.nickname }}</h6>
        <h6>작성시각 : {{ question.created_at | date:'Y.m.d H:i'}}</h6>
        {% if user.username == question.author.username %}
            <a href="{% url 'blog:modify' question.pk %}" class="btn btn-sm btn-primary">글수정</a>
        {% endif %}
    </div>
</div>


<h1>{{ question.subject }}</h1>
<hr>

<textarea class="form-control" name="content" id="content" rows="20" style="resize: none;" disabled>{{ question.content | default_if_none:'' | escape }}</textarea>


{% endblock %}

templates/blog/question_list.html
{% extends 'base.html' %}
{% block title %}메인화면{% endblock %}


{% block content %}


{% if question_list %}

<table class="table table-hover">
    <thead>
        <tr>
            <th>제목</th>
            <th>작성자</th>
            <th>시각</th>
        </tr>
    </thead>
    <tbody>
        {% for question in question_list %}
        <tr>
            <td><a href="{{ question.get_absolute_url }}">{{ question.subject | truncatechars:20 }}</a></td>
            <td>{{ question.author.nickname }}</td>
            <td>{{ question.created_at | date:"Y.m.d"}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% else %}
    <h1>No question</h1>
{% endif %}

{% endblock %}

templates/blog/question_write.html
{% extends 'base.html' %}
{% block title %}글작성{% endblock %}


{% block content %}



<form action="" method="post">
    {% csrf_token %}
    {% include 'errors.html' %}
    <label for="subject" class="form-label">제목</label>
    <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value | default_if_none:'' }}">
    <br>
    <textarea class="form-control" name="content" id="content" rows="20" style="resize: none;">{{ form.content.value | default_if_none:'' | escape }}</textarea>
    <input type="submit" class="btn btn-sm btn-primary mt-2" value="글등록">
</form>


{% endblock %}

templates/common/login.html
{% extends 'base.html' %}
{% block title %}로그인{% endblock %}


{% block content %}



<form action="" method="post">
    {% csrf_token %}
    {% include 'errors.html' %}
    <label for="username" class="form-label">계정</label>
    <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value | default_if_none:'' }}">
    <br>
    <label for="password" class="form-label">비밀번호</label>
    <input type="password" class="form-control" name="password" id="password">
    <input type="submit" class="btn btn-sm btn-primary mt-2" value="로그인">
</form>


{% endblock %}

templates/common/signup.html
{% extends 'base.html' %}
{% block title %}회원가입{% endblock %}


{% block content %}



<form action="" method="post">
    {% csrf_token %}
    {% include 'errors.html' %}
    <label for="username" class="form-label">계정</label>
    <input type="text" class="form-control" name="username" id="username">
    <br>
    <label for="password1" class="form-label">비밀번호</label>
    <input type="password" class="form-control" name="password1" id="password1">
    <br>
    <label for="password2" class="form-label">비밀번호 확인</label>
    <input type="password" class="form-control" name="password2" id="password2">
    <br>
    <label for="nickname" class="form-label">닉네임</label>
    <input type="text" class="form-control" name="nickname" id="nickname">
    <input type="submit" class="btn btn-sm btn-primary mt-2" value="회원가입">
</form>


{% endblock %}

templates/errors.html
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field in form %}
        {% if field.errors %}
        <div>
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
        </div>
        {% endif %}
    {% endfor %}
</div>
{% endif %}